ToDoList/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoList.Pages
{
    public class AboutModel : PageModel
    {
        private readonly ILogger<AboutModel> _logger;

        public AboutModel(ILogger<AboutModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ToDoList/Pages/GoogleLogin.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using ToDoList.DataAccess;

namespace ToDoList.Pages
{
    [AllowAnonymous]
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<ToDoListUser> _signInManager;
        private readonly UserManager<ToDoListUser> _userManager;
        //private readonly IEmailSender _emailSender;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<ToDoListUser> signInManager,
            UserManager<ToDoListUser> userManager,
            ILogger<ExternalLoginModel> logger
            //IEmailSender emailSender
            )
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
           // _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ProviderDisplayName { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [StringLength(100)]
            //[RegularExpression("^(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$", ErrorMessage = "Username can contain only english letters, numbers, dots and underscore")]
            public string UserName { get; set; }

            //[Required]
            //[EmailAddress]
            //public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Login");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./GoogleLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            try
            {
                returnUrl = returnUrl ?? Url.Content("~/");
                if (remoteError != null)
                {
                    ErrorMessage = $"Error from external provider: {remoteError}";
                    return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
                }
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    ErrorMessage = "Error loading external login information.";
                    return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
                }

                // Sign in the user with this external login provider if the user already has a login.
                var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                    return LocalRedirect(returnUrl);
                }
                if (result.IsLockedOut)
                {
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    // If the user does not have an account, then ask the user to create an account.
                    ReturnUrl = returnUrl;
                    ProviderDisplayName = info.ProviderDisplayName;
                    if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                    {
                        Input = new InputModel
                        {
                            //Email = info.Principal.FindFirstValue(ClaimTypes.Email),
                            UserName = info.Principal.FindFirstValue(ClaimTypes.Email)
                        };
                    }
                    return Page();
                }
            }
            catch (Exception e)
            {
                _logger.LogCritical(e.Message, e);
                await _signInManager.SignOutAsync();
                return RedirectToPage("/Error");
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            // Get the information about the user from the external login provider
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information during confirmation.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            if (ModelState.IsValid)
            {
                var user = new ToDoListUser { UserName = Input.UserName, Email = info.Principal.FindFirstValue(ClaimTypes.Email) };

                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);

                        //var userId = await _userManager.GetUserIdAsync(user);
                        //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                        //code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                        //var callbackUrl = Url.Page(
                        //    "/Account/ConfirmEmail",
                        //    pageHandler: null,
                        //    values: new { area = "Identity", userId, code },
                        //    protocol: Request.Scheme);

                        //await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        //    $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                        // If account confirmation is required, we need to show the link if we don't have a real email sender
                        if (_userManager.Options.SignIn.RequireConfirmedAccount)
                        {
                            return RedirectToPage("./RegisterConfirmation", new { Input.UserName });
                        }

                        await _signInManager.SignInAsync(user, isPersistent: false, info.LoginProvider);

                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            ProviderDisplayName = info.ProviderDisplayName;
            ReturnUrl = returnUrl;
            return Page();
        }
    }
}

ToDoList/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;
using ToDoList.Models;
using Microsoft.AspNetCore.Identity;
using ToDoList.DataAccess;
using System.Security.Claims;
using ToDoList.Controllers;

namespace ToDoList.Pages
{
    [SaveTempData]
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ToDoService _toDoService;
        //private readonly HttpClient _httpClient;
        //private readonly UserManager<ToDoListUser> _userManager;


        public IndexModel(ILogger<IndexModel> logger, ToDoService toDoService, UserManager<ToDoListUser> UserManager)
        {
            _logger = logger;
            _toDoService = toDoService;
            //_httpClient = client.CreateClient("baseHttp");
            //_userManager = UserManager;
            //_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(User.)
        }

        [TempData]
        public string ToDosJson { get; set; }

        public List<List<ToDoDto>> ToDos { get; set; }

        
        [BindProperty]
        public ToDoDto? SelectedToDo { get; set; }

        //[TempData]
        //public string SelectedWeekString { get; set; }

        [TempData]
        public DateTime SelectedWeek { get; set; }

        [ValidateNever]
        [BindProperty]
        public DayOfWeek SelectedDay { get; set; }

        [BindProperty]
        public string SelectedGuid { get; set; }

        public async Task<IActionResult> OnGetAsync(DateTime? date)
        {
            try
            {
                if (date != null) SelectedWeek = (DateTime) date;
                if (SelectedWeek == default) SelectedWeek = DateTime.Now - TimeSpan.FromDays((int)DateTime.Now.DayOfWeek);

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var response = _toDoService.GetWeekToDos(SelectedWeek, userId);
                  // await _httpClient.GetFromJsonAsync<IEnumerable<ToDoDto>>($"/api/ToDo/{userId}/{SelectedWeek.Date:yyyy-MM-dd}");


                ToDos = SortToDos(response);
                ToDosJson = JsonConvert.SerializeObject(ToDos);
                TempData.Keep();
                return Page();
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);

                ToDos = new List<List<ToDoDto>>();
                //return Page();
                return RedirectToPage("/Error");
            }

        }


        public IActionResult OnPostNextWeekAsync()
        {
            try
            {
                SelectedWeek = SelectedWeek.AddDays(7);
                return RedirectToPage(SelectedWeek);
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return RedirectToPage("/Error");
            }
        }

        public IActionResult OnPostPrevWeekAsync()
        {
            try
            {
                SelectedWeek = SelectedWeek.Subtract(TimeSpan.FromDays(7));
                return RedirectToPage(SelectedWeek);
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return RedirectToPage("/Error");
            }
        }

        public async Task<IActionResult> OnPostChangeDayAsync()
        {
            try
            {
                ToDos = JsonConvert.DeserializeObject<List<List<ToDoDto>>>(ToDosJson);
                if (ToDos != null)
                {
                    if (SelectedWeek == default) SelectedWeek = DateTime.Now - TimeSpan.FromDays((int)DateTime.Now.DayOfWeek);
                    SelectedToDo = (from todoList in ToDos
                        from toDo in todoList
                        where toDo.ToDoGuid == Guid.Parse(SelectedGuid)
                        select toDo).First();
                    var newDate = SelectedWeek.AddDays((int) SelectedDay);
                    SelectedToDo.Date = new DateTime(newDate.Year, newDate.Month, newDate.Day , SelectedToDo.Date.Hour,
                        SelectedToDo.Date.Minute, DateTime.Now.Second, DateTime.Now.Millisecond);
                    _toDoService.EditToDo(SelectedToDo);
                    //await _httpClient.PostAsJsonAsync<ToDoDto>("/api/ToDo/Edit", SelectedToDo);
                }
                return RedirectToPage(SelectedWeek);

            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return RedirectToPage("/Error");
            }
        }

        public async Task<IActionResult> OnPostEditAsync()
        {
            try
            {
                ToDos = JsonConvert.DeserializeObject<List<List<ToDoDto>>>(ToDosJson);
                if (ToDos != null)
                {
                    TryValidateModel(SelectedToDo);
                    if (ModelState.GetValidationState(nameof(SelectedToDo.Name)) == ModelValidationState.Invalid || ModelState.GetValidationState(nameof(SelectedToDo.Date)) == ModelValidationState.Invalid)
                    {
                        return RedirectToPage(SelectedWeek);
                    }
                    var oldToDo = (from todoList in ToDos
                        from toDo in todoList
                        where toDo.ToDoGuid == SelectedToDo.ToDoGuid
                        select toDo).First();
                    oldToDo.Date = oldToDo.Date.Subtract(new TimeSpan(oldToDo.Date.Hour, oldToDo.Date.Minute, 0));
                    oldToDo.Date = oldToDo.Date.Add(new TimeSpan(SelectedToDo.Date.Hour, SelectedToDo.Date.Minute, 0));
                    SelectedToDo.Date = oldToDo.Date;
                    //await _httpClient.PostAsJsonAsync<ToDoDto>("/api/ToDo/Edit", SelectedToDo);
                    _toDoService.EditToDo(SelectedToDo);
                }
                return RedirectToPage(SelectedWeek);

            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return RedirectToPage("/Error");
            }
        }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            try
            {
                if (SelectedToDo != default)
                {
                    _toDoService.DeleteToDo(SelectedToDo.ToDoGuid);
                    //await _httpClient.DeleteAsync($"/api/ToDo/{SelectedToDo.ToDoGuid}");
                }
                return RedirectToPage(SelectedWeek);
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return RedirectToPage("/Error");
            }
        }

        public IActionResult OnPostSelectToDo()
        {

            ToDos =  JsonConvert.DeserializeObject<List<List<ToDoDto>>>(ToDosJson);
            if (ToDos != null)
            {
                foreach (var todoList in ToDos)
                {
                    if (todoList.Exists(x => x.ToDoGuid.ToString() == SelectedGuid)) SelectedToDo = todoList.Find(x => x.ToDoGuid.ToString() == SelectedGuid);
                }
                SelectedToDo.Date = DateTime.Parse(SelectedToDo.Date.ToString("g"));
                TempData.Keep();
                return Page(); 
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                TryValidateModel(SelectedToDo);
                if (ModelState.GetValidationState(nameof(SelectedToDo)) == ModelValidationState.Invalid || ModelState.GetValidationState(nameof(SelectedToDo.Date)) == ModelValidationState.Invalid)
                {
                    RedirectToPage();
                }
                if (SelectedWeek == default) SelectedWeek = DateTime.Now - TimeSpan.FromDays((int)DateTime.Now.DayOfWeek);
                var selectedDate = SelectedWeek.AddDays((int) SelectedDay);
                SelectedToDo.Date = new DateTime(selectedDate.Year, selectedDate.Month, selectedDate.Day, SelectedToDo.Date.Hour,
                    SelectedToDo.Date.Minute, DateTime.Now.Second, DateTime.Now.Millisecond);

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                //await _httpClient.PostAsJsonAsync($"/api/ToDo/{userId}", SelectedToDo);
                _toDoService.AddToDo(SelectedToDo, userId);
                return RedirectToPage(SelectedWeek);
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                return RedirectToPage("/Error");
            }

        }

        private List<List<ToDoDto>> SortToDos(IEnumerable<ToDoDto> toDos)
        {
            var result = new List<List<ToDoDto>>();
            foreach (DayOfWeek weekDay in (DayOfWeek[])Enum.GetValues(typeof(DayOfWeek)))
            {
                result.Add(toDos.Where(x => x.Date.DayOfWeek == weekDay).ToList());
            }
            return result;
        }
    }
}

ToDoList/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h1 class="display-3">@ViewData["Title"]</h1>

<p class="display-6">This is a simple ToDo list app</p>
<section>
    To add a new ToDo just double click on the day of your desire. After that, fill out the form and click save button. <br/>
    You can edit and view ToDo by clicking it once. You can also change the day of todo by dragging it.
</section>

ToDoList/Pages/GoogleLogin.cshtml
@page
@model ExternalLoginModel
@{
    ViewData["Title"] = "Register";
}

<h1>@ViewData["Title"]</h1>
<h4 id="external-login-title">Associate your @Model.ProviderDisplayName account.</h4>
<hr />

<p id="external-login-description" class="text-info">
    You've successfully authenticated with <strong>@Model.ProviderDisplayName</strong>.
    Please enter an email address for this site below and click the Register button to finish
    logging in.
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  asp-for="Input.UserName">Username</label>
                <input asp-for="Input.UserName" class="form-control" />
                <span asp-validation-for="Input.UserName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Register</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ToDoList/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}



<link type="text/css" rel="stylesheet"  href="~/css/ToDo.css"/>
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
<div class="text-center" style="width: 90%; margin: 0 auto; height: 100%; display: flex; flex-flow: column">
    <h3 class="display-6" align="left">@(Model.SelectedWeek.ToString("MMM")[0].ToString().ToUpper() + Model.SelectedWeek.ToString("MMM").Substring(1)). @(Model.SelectedWeek.Year)</h3>
    
    <div class="row flex-nowrap" style="flex: 1 1 auto">
        <div class="col-1 d-flex align-items-center">
            <form asp-page-handler="prevWeek" class="align-middle" method="post">
                <button type="submit" class="btn btn-outline-secondary align-items-center rounded-pill">
                    <span class="material-icons text-center align-middle">arrow_back_ios</span>
                </button>
            </form>
        </div>
        <div class="col-10" >
            <div class="row flex-nowrap overflow-auto" style="height: 100%">

                @foreach (var dayTodos in Model.ToDos)
                {
                    <div id="@(Model.ToDos.IndexOf(dayTodos))-dayToDo" class="col dayToDo" style="width: 14.3%; display: block;height: 100%">
                        <h3 class="d-none d-xxl-block " draggable="false">@((DayOfWeek) Model.ToDos.IndexOf(dayTodos))</h3>
                        <h3 class="d-none d-xl-block d-xxl-none" draggable="false">@(((DayOfWeek)Model.ToDos.IndexOf(dayTodos)).ToString()[..3])</h3>
                        <h3 class="d-xl-none" draggable="false">@(((DayOfWeek)Model.ToDos.IndexOf(dayTodos)).ToString()[0])</h3>
                        <h5 draggable="false">@(Model.SelectedWeek.AddDays(Model.ToDos.IndexOf(dayTodos)).Day)</h5>
                        <ul id="dayToDoUl" class="todoUl list-group list-group-flush ">
                            @foreach (var todo in dayTodos)
                            {
                                <li id="@todo.ToDoGuid" class="list-group-item todo overflow-hidden" draggable="true">
                                    @(todo.Name?.Length > 15 ? todo.Name[..14]+".." : todo.Name)
                                </li>
                            }
                        </ul>
                    </div>
                    @if (Model.ToDos[^1] != dayTodos)
                    {
                        <div class="vr" style="padding-left: 0; padding-right: 0"></div>
                    }
                }
            </div>
        </div>
        <div class="col-1 d-flex align-items-center">
            <form asp-page-handler="nextWeek" method="post">
                <button type="submit" class="btn btn-outline-secondary align-items-center rounded-pill">
                    <span class="material-icons align-middle">arrow_forward_ios</span>
                </button>
            </form>
        </div>
    </div>

    
    

    <div class="modal fade" id="ToDoModal" tabindex="-1" role="dialog" aria-labelledby="ToDoModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Add ToDo</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span hidden="true" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="AddToDo" asp-page-handler="" method="post">
                        <div class="form-group">
                            <label for="todoTitle" class="form-label">ToDo's Title</label>
                            <input type="text" asp-for="SelectedToDo.Name" class="form-control" id="todoTitle" aria-describedby="toDoNameHelp" placeholder="Enter Title" required>
                        </div>
                        <div class="form-group">
                            <label for="todoDescription" class="form-label">ToDo's Description</label>
                            <textarea asp-for="SelectedToDo.Description" class="form-control" id="todoDescription" rows="3" placeholder="Enter Description" ></textarea>
                        </div>
                        <div class="form-group">
                            <label for="todoDate" class="form-label">ToDo's hour</label>
                            <input type="time" asp-for="SelectedToDo.Date" step="60" class="form-control" id="todoDate" aria-describedby="toDoDateHelp" placeholder="Enter hour" required>

                        </div>
                        <input id="dayInput" type="number" min="0" max="6" asp-for="SelectedDay" hidden="true" aria-hidden="True"/>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" id="AddToDoSubmit" form="AddToDo" class="btn btn-primary">Add ToDo</button>
                </div>
            </div>
        </div>
    </div>
    

    <div class="modal fade" id="ToDoEditModal" tabindex="-1" role="dialog" aria-labelledby="ToDoModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalCenterTitle">Edit ToDo</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span hidden="true" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="EditToDo" asp-page-handler="edit" method="post">
                        <div class="form-group">
                            <label for="todoEditTitle" class="form-label">ToDo's Title</label>
                            <input type="text" asp-for="SelectedToDo.Name" class="form-control" id="todoEditTitle" aria-describedby="toDoNameHelp" placeholder="Enter Title" required>

                        </div>
                        <div class="form-group">
                            <label for="todoEditDescription" class="form-label">ToDo's Description</label>
                            <textarea asp-for="SelectedToDo.Description" class="form-control" id="todoEditDescription" rows="3" placeholder="Enter Description"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="todoEditDate" class="form-label">ToDo's hour</label>
                            <input type="time" asp-for="SelectedToDo.Date" step="60" class="form-control" id="todoEditDate" aria-describedby="toDoDateHelp" placeholder="Enter hour" required>

                        </div>
                        <input id="dayInput" type="number" min="0" max="6" asp-for="SelectedDay" hidden="true" aria-hidden="True" />
                        <input id="ToDoGuidEditInput" type="text" asp-for="SelectedToDo.ToDoGuid" hidden="true" value="@Model.SelectedGuid" aria-hidden="True" />
                    </form>
                </div>
                <div class="modal-footer">
                    <form asp-page-handler="delete" method="post">
                        <div class="align-items-start align-self-start">
                            <button type="submit" class="btn btn-danger " id="deleteToDo">Delete ToDo</button>
                        </div>
                        <input id="ToDoGuidDeleteInput" type="text" asp-for="SelectedToDo.ToDoGuid" hidden="true" value="@Model.SelectedGuid" aria-hidden="True"/>
                    </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" id="EditToDoSubmit" form="EditToDo" class="btn btn-primary">Save ToDo</button>
                </div>
            </div>
        </div>
    </div>
    


    <form asp-page-handler="changeDay" method="post">
        <input hidden="true" id="changeToDayInput" type="number" asp-for="@Model.SelectedDay"/>
        <input hidden="true" id="toDoGuidInput" type="text" asp-for="@Model.SelectedGuid"/>
        <button id="dayChangeSubmit" hidden="true"></button>
    </form>
    
    <form asp-page-handler="selectToDo" method="post">
        <input hidden="true" id="selectToDoGuidInput" type="text" asp-for="@Model.SelectedGuid"/>
        <button id="selectToDoSubmit" hidden="true">
        </button>
    </form>


    <script>
        var clickedDay = null;
        document.querySelectorAll('.dayToDo').forEach(day => {
            day.addEventListener('dblclick',
                (e) => {
                    $('#AddToDo').find("[name*='SelectedToDo.']").val("");
                    $("#ToDoModal").modal('show');
                    clickedDay = day.id.split('-')[0];

                    document.querySelector('#dayInput').value = parseInt(clickedDay);
                });
        });


        var dayToDos = document.querySelectorAll('.dayToDo');
        var toDos = document.querySelectorAll('.todo');
        var dragged = null;
        document.querySelectorAll('.todo').forEach(todo => {
            todo.addEventListener('drag',
                () => {
                    dragged = todo;
                });
        });
        dayToDos.forEach(day => {
            day.addEventListener('dragover',
                (e) => {
                    e.preventDefault();
                });
            day.addEventListener('drop',
                (e) => {
                    e.preventDefault();
                    dragged.parentNode.removeChild(dragged);
                    day.querySelector('#dayToDoUl').appendChild(dragged);
                    document.querySelector('#toDoGuidInput').value = dragged.id;
                    document.querySelector('#changeToDayInput').value = parseInt(day.id.split('-')[0]);
                    document.querySelector('#dayChangeSubmit').form.submit();
                });
        });
        
        toDos.forEach(todo => {
            todo.addEventListener('click', () => {
                document.querySelector('#selectToDoGuidInput').value = todo.id;
                document.querySelector('#selectToDoSubmit').form.submit();
            })
        })
    </script>

    @if (Model.SelectedToDo != default)
    {
        <script>
            $(document).ready(function () {
                $("#ToDoEditModal").modal('show');
            });
        </script>
    }
</div>

ToDoList/Pages/Logout.cshtml
@page
@model LogoutModel
@{
    ViewData["Title"] = "Log out";
}

<header>
    <h1>@ViewData["Title"]</h1>
    <p>You have successfully logged out of the application.</p>
</header>